---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: oracle-7.3

suites:
  - name: test-a
    run_list:
      - recipe[kitchen-example::default]
    verifier:
      inspec_tests:
        - test/smoke/test-a
    attributes:
    provisioner:
        nodes_path: test/smoke/test-a/nodes
  - name: test-b
    run_list:
      - recipe[kitchen-example::default]
    verifier:
      inspec_tests:
        - test/smoke/test-b
    attributes:
    provisioner:
        nodes_path: test/smoke/test-b/nodes
